# Generated by Django 3.0.7 on 2020-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nawyki',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
