# Generated by Django 3.0.7 on 2020-06-26 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_auto_20200626_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nawyki',
            name='koniec',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
