# Generated by Django 3.0.7 on 2020-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0003_auto_20200626_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nawyki',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
