# Generated by Django 3.0.7 on 2020-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0005_auto_20200626_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nawyki',
            name='dzisiaj_zrobione',
            field=models.BooleanField(),
        ),
    ]
