# Generated by Django 3.0.7 on 2020-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0006_auto_20200626_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nawyki',
            name='dzisiaj_zrobione',
            field=models.BooleanField(default=False),
        ),
    ]
