# Generated by Django 3.0.7 on 2020-07-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0007_auto_20200630_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nawyki',
            name='dzisiaj_zrobione',
        ),
        migrations.RemoveField(
            model_name='nawyki',
            name='zrobione',
        ),
        migrations.CreateModel(
            name='Daty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('idNawyki', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='konta.Nawyki')),
            ],
        ),
    ]
