# Generated by Django 3.0.7 on 2020-07-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0008_auto_20200703_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daty',
            name='idNawyki',
        ),
    ]
