# Generated by Django 3.0.7 on 2020-07-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0009_remove_daty_idnawyki'),
    ]

    operations = [
        migrations.AddField(
            model_name='daty',
            name='idNawyki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='konta.Nawyki'),
            preserve_default=False,
        ),
    ]
